print("bài toán về số nhỏ nhất và số lớn nhất")
import math
a=eval(input("nhập số a: "))
b=eval(input("nhập số b: "))
c=eval(input("nhập số c: "))
d=eval(input("nhập số c: "))
g=max(a,b,c,d)
h=min(a,b,c,d)
print("max=",g)
print("min=",h)